<?php
/**
 * Copyright Di Nkomo(TM) 2016, all rights reserved
 *
 */
use Illuminate\Database\Seeder;

use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->command->info('Seeding countries...');

        Country::firstOrCreate(['name' => 'Afghanistan', 'code' => 'AF', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Albania', 'code' => 'AL', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Algeria', 'code' => 'DZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'American Samoa', 'code' => 'AS', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Andorra', 'code' => 'AD', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Angola', 'code' => 'AO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Anguilla', 'code' => 'AI', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Antarctica', 'code' => 'AQ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Antigua and Barbuda', 'code' => 'AG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Argentina', 'code' => 'AR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Armenia', 'code' => 'AM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Aruba', 'code' => 'AW', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Australia', 'code' => 'AU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Austria', 'code' => 'AT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Azerbaijan', 'code' => 'AZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Bahamas', 'code' => 'BS', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Bahrain', 'code' => 'BH', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Bangladesh', 'code' => 'BD', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Barbados', 'code' => 'BB', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Belarus', 'code' => 'BY', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Belgium', 'code' => 'BE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Belize', 'code' => 'BZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Benin', 'code' => 'BJ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Bermuda', 'code' => 'BM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Bhutan', 'code' => 'BT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Bolivia', 'code' => 'BO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Botswana', 'code' => 'BW', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Bouvet Island', 'code' => 'BV', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Brazil', 'code' => 'BR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'British Antarctic Territory', 'code' => 'BQ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'British Virgin Islands', 'code' => 'VG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Brunei', 'code' => 'BN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Bulgaria', 'code' => 'BG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Burkina Faso', 'code' => 'BF', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Burundi', 'code' => 'BI', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Cambodia', 'code' => 'KH', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Cameroon', 'code' => 'CM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Canada', 'code' => 'CA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Canton and Enderbury Islands', 'code' => 'CT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Cape Verde', 'code' => 'CV', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Cayman Islands', 'code' => 'KY', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Central African Republic', 'code' => 'CF', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Chad', 'code' => 'TD', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Chile', 'code' => 'CL', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'China', 'code' => 'CN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Christmas Island', 'code' => 'CX', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Cocos [Keeling] Islands', 'code' => 'CC', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Colombia', 'code' => 'CO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Comoros', 'code' => 'KM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Congo - Brazzaville', 'code' => 'CG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Congo - Kinshasa', 'code' => 'CD', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Cook Islands', 'code' => 'CK', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Costa Rica', 'code' => 'CR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Croatia', 'code' => 'HR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Cuba', 'code' => 'CU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Cyprus', 'code' => 'CY', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Czech Republic', 'code' => 'CZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'alt_names' => 'Cote d\'Ivoire; Ivory Coast']);
        Country::firstOrCreate(['name' => 'Denmark', 'code' => 'DK', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Djibouti', 'code' => 'DJ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Dominica', 'code' => 'DM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Dominican Republic', 'code' => 'DO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Dronning Maud Land', 'code' => 'NQ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'East Germany', 'code' => 'DD', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Ecuador', 'code' => 'EC', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Egypt', 'code' => 'EG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'El Salvador', 'code' => 'SV', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Equatorial Guinea', 'code' => 'GQ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Eritrea', 'code' => 'ER', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Estonia', 'code' => 'EE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Ethiopia', 'code' => 'ET', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Falkland Islands', 'code' => 'FK', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Faroe Islands', 'code' => 'FO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Fiji', 'code' => 'FJ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Finland', 'code' => 'FI', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'France', 'code' => 'FR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'French Guiana', 'code' => 'GF', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'French Polynesia', 'code' => 'PF', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'French Southern Territories', 'code' => 'TF', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'French Southern and Antarctic Territories', 'code' => 'FQ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Gabon', 'code' => 'GA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Gambia', 'code' => 'GM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Georgia', 'code' => 'GE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Germany', 'code' => 'DE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Ghana', 'code' => 'GH', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Gibraltar', 'code' => 'GI', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Greece', 'code' => 'GR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Greenland', 'code' => 'GL', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Grenada', 'code' => 'GD', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Guadeloupe', 'code' => 'GP', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Guam', 'code' => 'GU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Guatemala', 'code' => 'GT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Guernsey', 'code' => 'GG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Guinea', 'code' => 'GN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Guinea-Bissau', 'code' => 'GW', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Guyana', 'code' => 'GY', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Haiti', 'code' => 'HT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Heard Island and McDonald Islands', 'code' => 'HM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Honduras', 'code' => 'HN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Hong Kong SAR China', 'code' => 'HK', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Hungary', 'code' => 'HU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Iceland', 'code' => 'IS', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'India', 'code' => 'IN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Indonesia', 'code' => 'ID', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Iran', 'code' => 'IR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Iraq', 'code' => 'IQ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Ireland', 'code' => 'IE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Isle of Man', 'code' => 'IM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Israel', 'code' => 'IL', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Italy', 'code' => 'IT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Jamaica', 'code' => 'JM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Japan', 'code' => 'JP', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Jersey', 'code' => 'JE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Johnston Island', 'code' => 'JT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Jordan', 'code' => 'JO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Kazakhstan', 'code' => 'KZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Kenya', 'code' => 'KE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Kiribati', 'code' => 'KI', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Kuwait', 'code' => 'KW', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Kyrgyzstan', 'code' => 'KG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Laos', 'code' => 'LA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Latvia', 'code' => 'LV', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Lebanon', 'code' => 'LB', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Lesotho', 'code' => 'LS', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Liberia', 'code' => 'LR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Libya', 'code' => 'LY', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Liechtenstein', 'code' => 'LI', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Lithuania', 'code' => 'LT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Luxembourg', 'code' => 'LU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Macau SAR China', 'code' => 'MO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Macedonia', 'code' => 'MK', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Madagascar', 'code' => 'MG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Malawi', 'code' => 'MW', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Malaysia', 'code' => 'MY', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Maldives', 'code' => 'MV', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Mali', 'code' => 'ML', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Malta', 'code' => 'MT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Marshall Islands', 'code' => 'MH', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Martinique', 'code' => 'MQ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Mauritania', 'code' => 'MR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Mauritius', 'code' => 'MU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Mayotte', 'code' => 'YT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Metropolitan France', 'code' => 'FX', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Mexico', 'code' => 'MX', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Micronesia', 'code' => 'FM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Midway Islands', 'code' => 'MI', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Moldova', 'code' => 'MD', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Monaco', 'code' => 'MC', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Mongolia', 'code' => 'MN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Montenegro', 'code' => 'ME', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Montserrat', 'code' => 'MS', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Morocco', 'code' => 'MA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Mozambique', 'code' => 'MZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Myanmar [Burma]', 'code' => 'MM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Namibia', 'code' => 'NA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Nauru', 'code' => 'NR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Nepal', 'code' => 'NP', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Netherlands', 'code' => 'NL', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Netherlands Antilles', 'code' => 'AN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Neutral Zone', 'code' => 'NT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'New Caledonia', 'code' => 'NC', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'New Zealand', 'code' => 'NZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Nicaragua', 'code' => 'NI', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Niger', 'code' => 'NE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Nigeria', 'code' => 'NG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Niue', 'code' => 'NU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Norfolk Island', 'code' => 'NF', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'North Korea', 'code' => 'KP', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'North Vietnam', 'code' => 'VD', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Northern Mariana Islands', 'code' => 'MP', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Norway', 'code' => 'NO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Oman', 'code' => 'OM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Pacific Islands Trust Territory', 'code' => 'PC', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Pakistan', 'code' => 'PK', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Palau', 'code' => 'PW', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Palestinian Territories', 'code' => 'PS', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Panama', 'code' => 'PA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Panama Canal Zone', 'code' => 'PZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Papua New Guinea', 'code' => 'PG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Paraguay', 'code' => 'PY', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'People\'s Democratic Republic of Yemen', 'code' => 'YD', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Peru', 'code' => 'PE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Philippines', 'code' => 'PH', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Pitcairn Islands', 'code' => 'PN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Poland', 'code' => 'PL', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Portugal', 'code' => 'PT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Puerto Rico', 'code' => 'PR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Qatar', 'code' => 'QA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Romania', 'code' => 'RO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Russia', 'code' => 'RU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Rwanda', 'code' => 'RW', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Réunion', 'code' => 'RE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Saint Barthélemy', 'code' => 'BL', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Saint Helena', 'code' => 'SH', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Saint Lucia', 'code' => 'LC', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Saint Martin', 'code' => 'MF', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Samoa', 'code' => 'WS', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'San Marino', 'code' => 'SM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Saudi Arabia', 'code' => 'SA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Senegal', 'code' => 'SN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Serbia', 'code' => 'RS', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Serbia and Montenegro', 'code' => 'CS', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Seychelles', 'code' => 'SC', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Sierra Leone', 'code' => 'SL', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Singapore', 'code' => 'SG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Slovakia', 'code' => 'SK', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Slovenia', 'code' => 'SI', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Solomon Islands', 'code' => 'SB', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Somalia', 'code' => 'SO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'South Africa', 'code' => 'ZA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'South Korea', 'code' => 'KR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Spain', 'code' => 'ES', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Sri Lanka', 'code' => 'LK', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Sudan', 'code' => 'SD', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Suriname', 'code' => 'SR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Swaziland', 'code' => 'SZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Sweden', 'code' => 'SE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Switzerland', 'code' => 'CH', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Syria', 'code' => 'SY', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'São Tomé and Príncipe', 'code' => 'ST', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Taiwan', 'code' => 'TW', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Tajikistan', 'code' => 'TJ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Tanzania', 'code' => 'TZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Thailand', 'code' => 'TH', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Timor-Leste', 'code' => 'TL', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Togo', 'code' => 'TG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Tokelau', 'code' => 'TK', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Tonga', 'code' => 'TO', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Trinidad and Tobago', 'code' => 'TT', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Tunisia', 'code' => 'TN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Turkey', 'code' => 'TR', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Turkmenistan', 'code' => 'TM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Tuvalu', 'code' => 'TV', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'U.S. Minor Outlying Islands', 'code' => 'UM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'U.S. Miscellaneous Pacific Islands', 'code' => 'PU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'U.S. Virgin Islands', 'code' => 'VI', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Uganda', 'code' => 'UG', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Ukraine', 'code' => 'UA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Union of Soviet Socialist Republics', 'code' => 'SU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'United Arab Emirates', 'code' => 'AE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'United Kingdom', 'code' => 'GB', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'United States', 'code' => 'US', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Unknown or Invalid Region', 'code' => 'ZZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Uruguay', 'code' => 'UY', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Uzbekistan', 'code' => 'UZ', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Vanuatu', 'code' => 'VU', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Vatican City', 'code' => 'VA', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Venezuela', 'code' => 'VE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Vietnam', 'code' => 'VN', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Wake Island', 'code' => 'WK', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Wallis and Futuna', 'code' => 'WF', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Western Sahara', 'code' => 'EH', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Yemen', 'code' => 'YE', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Zambia', 'code' => 'ZM', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Zimbabwe', 'code' => 'ZW', 'alt_names' => '']);
        Country::firstOrCreate(['name' => 'Åland Islands', 'code' => 'AX', 'alt_names' => '']);
    }
}
